AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This template is partially managed by Amazon.Lambda.Annotations (v1.5.2.0).
Resources:
  FlvtApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
        - http://localhost:5173
        AllowHeaders:
        - content-type
        AllowMethods:
        - POST
        MaxAge: 600
        AllowCredentials: false
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
    Metadata:
      SamResourceId: FlvtApi
  FinishedBatchesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: FinishedBatchesQueue
      VisibilityTimeout: 900
    Metadata:
      SamResourceId: FinishedBatchesQueue
  ScrapeAdvertisementsScrapAll:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: ScrapeAdvertisementsScrapAll
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: ScrapAll
      Runtime: dotnet8
      CodeUri: s3://flvt/8bd65500a41f78559e4c9a4b7af6dea6
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Flvt.API::Flvt.API.Functions.Background.ScrapeAdvertisements_ScrapAll_Generated::ScrapAll
      Events:
        ScheduleRule:
          Type: Schedule
          Properties:
            Name: ScrapAllSchedule
            Schedule: cron(0 0/6 * * ? *)
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: Lambda
            Destination:
              Fn::GetAtt:
              - ProcessAdvertisementsStartProcessing
              - Arn
  ProcessAdvertisementsStartProcessing:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: ProcessAdvertisementsStartProcessing
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: StartProcessing
      Runtime: dotnet8
      CodeUri: s3://flvt/8bd65500a41f78559e4c9a4b7af6dea6
      MemorySize: 3008
      Timeout: 300
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Flvt.API::Flvt.API.Functions.Background.ProcessAdvertisements_StartProcessing_Generated::StartProcessing
  ProcessAdvertisementsCheckProcessingStatus:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: ProcessAdvertisementsCheckProcessingStatus
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: CheckProcessingStatus
      Runtime: dotnet8
      CodeUri: s3://flvt/8bd65500a41f78559e4c9a4b7af6dea6
      MemorySize: 3008
      Timeout: 120
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Flvt.API::Flvt.API.Functions.Background.ProcessAdvertisements_CheckProcessingStatus_Generated::CheckProcessingStatus
      Events:
        ScheduleRule:
          Type: Schedule
          Properties:
            Name: CheckProcessingStatusSchedule
            Schedule: rate(30 minutes)
  ProcessAdvertisementsEndProcessing:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: ProcessAdvertisementsEndProcessing
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: EndProcessing
      Runtime: dotnet8
      CodeUri: s3://flvt/8bd65500a41f78559e4c9a4b7af6dea6
      MemorySize: 3008
      Timeout: 300
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Flvt.API::Flvt.API.Functions.Background.ProcessAdvertisements_EndProcessing_Generated::EndProcessing
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - FinishedBatchesQueue
              - Arn
  CustodyFunctionsRemoveOutdated:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: CustodyFunctionsRemoveOutdated
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: RemoveOutdated
      Runtime: dotnet8
      CodeUri: s3://flvt/8bd65500a41f78559e4c9a4b7af6dea6
      MemorySize: 3008
      Timeout: 300
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Flvt.API::Flvt.API.Functions.Background.CustodyFunctions_RemoveOutdated_Generated::RemoveOutdated
      Events:
        ScheduleRule:
          Type: Schedule
          Properties:
            Name: RemoveOutdatedSchedule
            Schedule: cron(0 1 * * ? *)
  CustodyFunctionsRemoveDuplicates:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: CustodyFunctionsRemoveDuplicates
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: RemoveDuplicates
      Runtime: dotnet8
      CodeUri: s3://flvt/8bd65500a41f78559e4c9a4b7af6dea6
      MemorySize: 3008
      Timeout: 300
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Flvt.API::Flvt.API.Functions.Background.CustodyFunctions_RemoveDuplicates_Generated::RemoveDuplicates
      Events:
        ScheduleRule:
          Type: Schedule
          Properties:
            Name: RemoveDuplicatesSchedule
            Schedule: cron(0 2 * * ? *)
  CustodyFunctionsUpdateUnprocessedScrapedAds:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: CustodyFunctionsUpdateUnprocessedScrapedAds
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: UpdateUnprocessedScrapedAds
      Runtime: dotnet8
      CodeUri: s3://flvt/8bd65500a41f78559e4c9a4b7af6dea6
      MemorySize: 3008
      Timeout: 300
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Flvt.API::Flvt.API.Functions.Background.CustodyFunctions_UpdateUnprocessedScrapedAds_Generated::UpdateUnprocessedScrapedAds
      Events:
        ScheduleRule:
          Type: Schedule
          Properties:
            Name: UpdateUnprocessedScrapedAdsSchedule
            Schedule: cron(0 3 * * ? *)
