AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "This template is partially managed by Amazon.Lambda.Annotations (v1.5.2.0)."

Resources:
  FlvtApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "http://localhost:5173"
        AllowHeaders:
          - content-type
        AllowMethods:
          - POST
        MaxAge: 600
        AllowCredentials: false 
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
  ProcessedAdvertisement:
    Type: "AWS::Serverless::Function"
    Metadata:
      Tool: "Amazon.Lambda.Annotations"
      SyncedEvents:
        - "RootPost"
      SyncedEventProperties:
        RootPost:
          - "Path"
          - "Method"
    Properties:
      Runtime: "dotnet8"
      CodeUri: "."
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role: !Ref arn:aws:iam::975049887576:role/FullAccess
      PackageType: "Zip"
      Handler: "Flvt.API::Flvt.API.Functions_ProcessNewAdvertisements_Generated::ProcessNewAdvertisements"
      Events:
      RootGet:
        Type: HttpApi
        Properties:
          Path: /v1
          Method: POST
          ApiId: !Ref FlvtApi

  ProcessAdvertisementsForUsers:
    Type: "AWS::Serverless::Function"
    Metadata:
      Tool: "Amazon.Lambda.Annotations"
    Properties:
      Runtime: "dotnet8"
      CodeUri: "."
      MemorySize: 512
      Timeout: 30
      Policies:
        - "AWSLambdaBasicExecutionRole"
      PackageType: "Zip"
      Handler: "Flvt.API::Flvt.API.Functions_ProcessAdvertisementsForUsers_Generated::ProcessAdvertisementsForUsers"
  FlvtLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: flvt
      RetentionInDays: 90
