AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: This template is partially managed by Amazon.Lambda.Annotations (v1.5.2.0).
Resources:
  FlvtApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "http://localhost:5173"
        AllowHeaders:
          - content-type
        AllowMethods:
          - POST
        MaxAge: 600
        AllowCredentials: false
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
  ProcessAdvertisementsStartProcessing:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: StartProcessing
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 3008
      Timeout: 900
      Policies: ''
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Flvt.API::Flvt.API.Functions.Background.ProcessAdvertisements_StartProcessing_Generated::StartProcessing
      Events:
        ScheduleRule:
          Type: Schedule
          Properties:
            Name: StartProcessingSchedule
          Schedule: 'cron(0 1/6 * * ? *)'
  ProcessAdvertisementsEndProcessing:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: EndProcessing
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Flvt.API::Flvt.API.Functions.Background.ProcessAdvertisements_EndProcessing_Generated::EndProcessing
      Events:
        ScheduleRule:
          Type: Schedule
          Properties:
            Name: EndProcessingSchedule
            Schedule: 'cron(0 2/6 * * ? *)'
  ScrapeAdvertisementsScrapAll:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: Flvt.API::Flvt.API.Functions.Background.ScrapeAdvertisements_ScrapAll_Generated::ScrapAll
